### ISSUE TITLE
App will not open anymore.

### ISSUE THREAD

**Issue by loli69B** [MalloyDelacroix/DownloaderForReddit#276]
When I set a date and time for the app to download in a schedule, it closed, and ever since then, it has never opened. 

Here is the log.
[DownloaderForReddit.log](https://github.com/MalloyDelacroix/DownloaderForReddit/files/7962409/DownloaderForReddit.log)

**Comment by zacker150** [comment]
Here is the relevant log entry:

```
Traceback (most recent call last):\n  
      File "main.py", line 104, in <module>
      File "main.py", line 75, in main
      File "DownloaderForReddit\utils\injector.py", line 59, in get_scheduler
      File "DownloaderForReddit\scheduling\scheduler.py", line 23, in __init__
      File "DownloaderForReddit\scheduling\scheduler.py", line 29, in load_tasks
      File "DownloaderForReddit\scheduling\scheduler.py", line 56, in schedule_task
      File "schedule\__init__.py", line 478, in at 
           schedule.ScheduleValueError: Invalid unit (valid units are `days`, `hours`, and `minutes`)
```

**Comment by loli69B** [comment]
I am using v.3.13.2 and I tried to schedule I think 2pm or 3pm weekly. I think I wrote it as military time so 13:00:00 or something like that.
