### ISSUE TITLE
Error on launch

### ISSUE THREAD

**Issue by oknitter** [MalloyDelacroix/DownloaderForReddit#387]
*Issues marked with the **Need Information** label will be closed after 30 days if additional information is not provided*
Receiving below error when application is launched. 

QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
asctime: 07/29/2024 05:36:24 PM
levelname: CRITICAL
name: DownloaderForReddit.__main__
message: Unhandled exception
exc_info: Traceback (most recent call last):
  File "/home/user/Programs/DownloaderForReddit/main.py", line 104, in <module>
    main()
  File "/home/user/Programs/DownloaderForReddit/main.py", line 77, in main
    window = DownloaderForRedditGUI(queue, receiver, scheduler)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/Programs/DownloaderForReddit/DownloaderForReddit/gui/downloader_for_reddit_gui.py", line 90, in __init__
    self.spinner = WaitingSpinner(self.user_list_view, roundness=80.0, opacity=10.0, fade=72.0, radius=10.0,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/Programs/DownloaderForReddit/DFREnv/lib/python3.11/site-packages/pyqtspinner/spinner.py", line 60, in __init__
    self.updateSize()
  File "/home/user/Programs/DownloaderForReddit/DFREnv/lib/python3.11/site-packages/pyqtspinner/spinner.py", line 204, in updateSize
    self.setFixedSize(size, size)
TypeError: arguments did not match any overloaded call:
  setFixedSize(self, QSize): argument 1 has unexpected type 'float'
  setFixedSize(self, int, int): argument 1 has unexpected type 'float'

**Comment by MalloyDelacroix** [comment]
Fixed by #414.
