### ISSUE TITLE
v2.3.2 at Linux - Core dump crash when I click "Subreddits save to folder designated by:" dropdown list at Settings menu

### ISSUE THREAD

**Issue by informer2016** [MalloyDelacroix/DownloaderForReddit#56]
I'm using DFR v2.3.2 at Linux and getting a core dump crash when I try to click "Subreddits save to folder designated by:" dropdown list at Settings menu. Here is the complete log:
```
levelname: INFO
message: User list changed to: Mini-Me
name: DownloaderForReddit.DownloaderForReddit.GUI.DownloaderForRedditGUI
asctime: 01/12/2019 22:11:27 

exc_info: Traceback (most recent call last):
  File "DownloaderForReddit/GUI/DownloaderForRedditGUI.py", line 613, in remove_user_list
  File "logging/__init__.py", line 1279, in info
  File "logging/__init__.py", line 1414, in _log
  File "logging/__init__.py", line 1388, in makeRecord
KeyError: "Attempt to overwrite 'name' in LogRecord"
levelname: WARNING
message: Unable to remove user list: No user list available to remove
name: DownloaderForReddit.DownloaderForReddit.GUI.DownloaderForRedditGUI
asctime: 01/12/2019 22:11:35 

levelname: INFO
message: Settings dialog opened
name: DownloaderForReddit.DownloaderForReddit.GUI.DownloaderForRedditSettingsGUI
asctime: 01/12/2019 22:12:16 

double free or corruption (out)

[5]-  Aborted                 (core dumped) ./DownloaderForReddit 
```

**Comment by MalloyDelacroix** [comment]
It looks like you are running the app from source.  Are you using the PyQt5 version listed in requirements.txt (v5.11.2)?
